name: CI

on:
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use Node version from .nvmrc and cache pnpm store
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      # Make pnpm available (and lock its version)
      - name: Enable corepack & pin pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.18.1 --activate
          pnpm --version

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build