name: CI

on:
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node from .nvmrc + cache
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      # Install pnpm (reliable on GitHub runners)
      - uses: pnpm/action-setup@v4
        with:
          version: 10.18.1
          run_install: false

      - name: Show versions
        run: |
          node -v
          pnpm -v

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
